---
- name: enabled telegraf service
  service:
    name: telegraf
    state: started
    enabled: yes

- name: restart telegraf service
  service:
    name: telegraf
    state: restarted

- name: "Restart Windows Telegraf"
  win_service:
    name: Telegraf
    start_mode: auto
    state: restarted