---
- name: install font requirements
  ansible.builtin.apt:
    name:
      - fontconfig
      - freetype*
      - fonts-texgyre
    state: present
  when: ansible_facts['os_family'] == "Debian"

- name: Add the Grafana GPG key and APT repository
  ansible.builtin.apt_repository:
    repo: deb https://packages.grafana.com/oss/deb stable main
    state: present
  when: ansible_facts['os_family'] == "Debian"

- name: Install Grafana
  ansible.builtin.apt:
    name: grafana
    state: present
  notify:
    - enabled grafana service
  when: ansible_facts['os_family'] == "Debian"
