#- name: setup repository
#  import_tasks: repo.yml

- name: Add the Grafana GPG key and APT repository
  shell: |
    curl https://packages.grafana.com/gpg.key | sudo apt-key add -
    add-apt-repository "deb https://packages.grafana.com/oss/deb stable main"
  args:
    warn: no

- name: install font requirements
  import_tasks: font.yml

- name: deploy grafana
  import_tasks: grafana.yml
