---
- name: deploy TIG stacks
  hosts: server
  become: true
  roles:
    - { role: telegraf, tags: telegraf }
    - { role: influxdb, tags: influxdb }
    - { role: grafana, tags: grafana }

- name: role telegraf agent
  hosts: windows
  roles:
    - telegraf

- name: role telegraf agent
  hosts: clients
  become: true
  roles:
    - grafana
    - influxdb
    - telegraf
