---
- name: add apt key InfluxData Repo
  apt_key:
    url: https://repos.influxdata.com/influxdb.key 
  when: ansible_facts['os_family'] == 'Debian'

- name: add InfluxData Repo
  apt_repository:
    repo: deb https://repos.influxdata.com/ubuntu focal stable
  when: ansible_facts['os_family'] == 'Debian'
