---
# description: MacOS specific installation

- name: "MacOS | set package name"
  ansible.builtin.set_fact:
    telegraf_agent_package: telegraf

- name: "MacOS | Install Telegraf package"
  ansible.builtin.package:
    name: telegraf
    state: present
  register: is_telegraf_package_installed
  until: is_telegraf_package_installed is succeeded
  notify: "Restart Telegraf"
