---
- name: Add telegraf repository
  ansible.builtin.yum_repository:
    name: influxdb
    description: InfluxDB Repository - RHEL $releasever
    baseurl: https://repos.influxdata.com/rhel/$releasever/$basearch/stable
    gpgcheck: true
    gpgkey: https://repos.influxdata.com/influxdb.key

- name: Install Telegraf packages [RHEL/CentOS]
  ansible.builtin.yum:
    name: telegraf
    state: present
    update_cache: true
