---
- template:
    src: telegraf.conf.j2
    dest: /etc/telegraf/telegraf.conf
  notify:
    - restart telegraf service

- name : checking if docker.sock exists
  stat:
    path: /var/run/docker.sock
  register: docker_file

- name: changing docker.sock permission to 666
  file:
    path: /var/run/docker.sock
    state: file
    owner: root
    group: root
    mode: "666"
  when: docker_file.stat.exists == true
